version: "3.8"

services:
  client:
    container_name: client-dev
    image: client-dev
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
  api:
    container_name: api-dev
    image: api-dev
    build:
        context: ./backend
        target: dev
    volumes:
      - ./backend/src:/app/src
    ports:
      - 8080:8080
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - '80:80'